### ISSUE TITLE
Roadmap: Document the Docs Release Process

### ISSUE THREAD

**Issue by chanmosq** [o3de/sig-docs-community#105]
### Summary

The sig-docs-community has a significant role in the O3DE Release Process. In short, they're responsible for all things regarding the documentation's release, including release notes. This process is partly documented in [Major Release Process](https://github.com/o3de/sig-release/blob/main/releases/Process/Major%20Release%20Process.md) or the old [22.10 Project Release board](https://github.com/o3de/o3de/projects/18).

This task is to document the docs release process, such that another member can follow the documentation to help with the release of the documentation portion of O3DE.

```[tasklist]
### Tasks
Work with sig-release to document the following in the [Major Release Process](https://github.com/o3de/sig-release/blob/main/releases/Process/Major%20Release%20Process.md) or the old [22.10 Project Release board](https://github.com/o3de/o3de/projects/18):
- [ ] https://github.com/o3de/sig-release/issues/108
- [ ] https://github.com/o3de/sig-release/issues/109
- [x] Work with SIG Release to publish docs
```
**Additional task details**
- [x] Per discussion [sig-release#108](https://github.com/o3de/sig-release/issues/108):
  - Responsibilities and ownership of maintaining the stabilization branch, which may include:
  - Creating the stabilization branch
  - Merging stabilization back to development (throughout stabilization phase)
  - Merging stabilization to main (on release day)
- [x] Per discussion [sig-release#109](https://github.com/o3de/sig-release/issues/109):
  - The Release Manager must review the release notes after the Docs Project Manager creates the release notes. All other technical SIGs should be optional reviewers as well.

**Output**

Updates to the [Major Release Process](https://github.com/o3de/sig-release/blob/main/releases/Process/Major%20Release%20Process.md) or the old [22.10 Project Release board](https://github.com/o3de/o3de/projects/18)

### Related Links
Link to additional information such as RFC related to the roadmap item.

---
_Learn more about [O3DE roadmaps](https://github.com/o3de/sig-release/issues/79)._
